spring.application.name=job-queue

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:jobqueue}
spring.datasource.username=${POSTGRES_USER:jobqueue}
spring.datasource.password=${POSTGRES_PASSWORD:jobqueue}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

management.endpoints.web.exposure.include=health
server.error.include-message=always
server.error.include-stacktrace=always

spring.kafka.bootstrap-servers=localhost:9092
